SQL> SELECT * FROM ordertable WHERE final_amount >= (SELECT
  2  AVG(final_amount) FROM ordertable);

  ORDER_ID ORDER_DAT DISCOUNT_AMOUNT TOTAL_AMOUNT FINAL_AMOUNT PAYMENT_METHOD       CUSTOMER_ID                                                                                                                                                                                                                                                                                                                 
---------- --------- --------------- ------------ ------------ -------------------- -----------                                                                                                                                                                                                                                                                                                                 
      2000 15-JAN-23           25.99       519.94       493.95 Esewa                          1                                                                                                                                                                                                                                                                                                                 
      2002 10-MAR-23               0       389.97       389.97 IME Pay                        3                                                                                                                                                                                                                                                                                                                 
      2006 15-MAY-23           44.99       899.99          855 IME Pay                        7                                                                                                                                                                                                                                                                                                                 
      2007 25-MAY-23           31.99       319.97       287.98 Cash                           2                                                                                                                                                                                                                                                                                                                 
      2011 08-JUN-23               0       339.97       339.97 Cash                          12                                                                                                                                                                                                                                                                                                                 
      2012 10-JUN-23           19.49       389.97       370.48 Esewa                         13                                                                                                                                                                                                                                                                                                                 
      2015 25-JUL-23               0       389.97       389.97 Cash                           9                                                                                                                                                                                                                                                                                                                 
      2016 05-AUG-23               0       389.97       389.97 Esewa                         18                                                                                                                                                                                                                                                                                                                 
      2017 15-AUG-23               0       479.97       479.97 Khalti                        18                                                                                                                                                                                                                                                                                                                 
      2021 14-SEP-23           19.49       349.97       330.48 Khalti                        13                                                                                                                                                                                                                                                                                                                 

10 rows selected.

SQL> spool off;
