SQL> SELECT *FROM customer c INNER JOIN ordertable o ON c.customer_id =
  2  o.customer_id;

CUSTOMER_ID CUSTOMER_NAME                                        DISCOUNT CUSTOMER_ADDRESS     CUSTOMER_PHONE       CUSTOMER_CATEGORY      ORDER_ID ORDER_DAT DISCOUNT_AMOUNT TOTAL_AMOUNT FINAL_AMOUNT PAYMENT_METHOD       CUSTOMER_ID                                                                    
----------- -------------------------------------------------- ---------- -------------------- -------------------- -------------------- ---------- --------- --------------- ------------ ------------ -------------------- -----------                                                                    
          1 Sita Basnet                                                 5 Kalanki              9841245672           Regular                    2000 15-JAN-23           25.99       519.94       493.95 Esewa                          1                                                                    
          2 Ramesh Shahi                                               10 Koteshwor            9841345678           Staff                      2001 20-FEB-23            4.99        49.97        44.98 Khalti                         2                                                                    
          3 Gita Thapa                                                  0 Bajaju               9841445673           VIP                        2002 10-MAR-23               0       389.97       389.97 IME Pay                        3                                                                    
          4 Bibek Bista                                                 5 Lazimpat             9841545674           Regular                    2003 05-APR-23            6.99       139.97       132.98 Cash                           4                                                                    
          5 Anita Rai                                                  10 Boudha               9841645675           VIP                        2004 01-MAY-23           23.99       239.97       215.98 Esewa                          5                                                                    
          3 Gita Thapa                                                  0 Bajaju               9841445673           VIP                        2005 08-MAY-23               0       129.97       129.97 Khalti                         3                                                                    
          7 Dilip Lama                                                  5 Jawalakhel           9841845677           Regular                    2006 15-MAY-23           44.99       899.99          855 IME Pay                        7                                                                    
          2 Ramesh Shahi                                               10 Koteshwor            9841345678           Staff                      2007 25-MAY-23           31.99       319.97       287.98 Cash                           2                                                                    
          9 Raju Maharjan                                               0 Gongabu              9842045679           Regular                    2008 27-MAY-23               0       119.97       119.97 Esewa                          9                                                                    
          4 Bibek Bista                                                 5 Lazimpat             9841545674           Regular                    2009 28-MAY-23           12.49       249.97       237.48 Khalti                         4                                                                    
         11 Prakash Magar                                              10 Kapan                9842245681           VIP                        2010 03-JUN-23            4.49        44.97        40.48 IME Pay                       11                                                                    
         12 Sumitra Joshi                                               0 Durbarmarg           9842345682           Regular                    2011 08-JUN-23               0       339.97       339.97 Cash                          12                                                                    
         13 Sabin Rai                                                   5 Balaju               9842445683           Regular                    2012 10-JUN-23           19.49       389.97       370.48 Esewa                         13                                                                    
         14 Pooja Khadka                                               10 Dhapasi              9842545684           VIP                        2013 14-JUN-23           17.99       179.97       161.98 Khalti                        14                                                                    
          9 Raju Maharjan                                               0 Gongabu              9842045679           Regular                    2014 20-JUL-23               0       149.97       149.97 IME Pay                        9                                                                    
          9 Raju Maharjan                                               0 Gongabu              9842045679           Regular                    2015 25-JUL-23               0       389.97       389.97 Cash                           9                                                                    
         18 Asmita Karki                                                0 Sanepa               9842945688           Staff                      2016 05-AUG-23               0       389.97       389.97 Esewa                         18                                                                    
         18 Asmita Karki                                                0 Sanepa               9842945688           Staff                      2017 15-AUG-23               0       479.97       479.97 Khalti                        18                                                                    
         18 Asmita Karki                                                0 Sanepa               9842945688           Staff                      2018 22-AUG-23               0        74.97        74.97 IME Pay                       18                                                                    
         18 Asmita Karki                                                0 Sanepa               9842945688           Staff                      2019 28-AUG-23               0       204.97       204.97 Cash                          18                                                                    
          6 Kiran Shrestha                                              0 Patan                9841745676           Staff                      2020 29-AUG-23               0       239.97       239.97 Esewa                          6                                                                    
         13 Sabin Rai                                                   5 Balaju               9842445683           Regular                    2021 14-SEP-23           19.49       349.97       330.48 Khalti                        13                                                                    
          2 Ramesh Shahi                                               10 Koteshwor            9841345678           Staff                      2022 20-OCT-23           23.99       239.97       215.98 IME Pay                        2                                                                    
          6 Kiran Shrestha                                              0 Patan                9841745676           Staff                      2023 28-NOV-23               0        89.97        89.97 Cash                           6                                                                    

24 rows selected.

SQL> SELECT * FROM customer WHERE customer_id NOT IN (SELECT
  2  c.customer_id FROM customer c INNER JOIN ordertable o ON c.customer_id =
  3  o.customer_id);

CUSTOMER_ID CUSTOMER_NAME                                        DISCOUNT CUSTOMER_ADDRESS     CUSTOMER_PHONE       CUSTOMER_CATEGORY                                                                                                                                                                       
----------- -------------------------------------------------- ---------- -------------------- -------------------- --------------------                                                                                                                                                                    
          8 Meena Tamang                                               10 Thamel               9841945678           VIP                                                                                                                                                                                     
         15 Alok Shrestha                                               0 Baneshwor            9842645685           Staff                                                                                                                                                                                   
         19 Roshan Shrestha                                             5 Swayambhu            9843045689           Regular                                                                                                                                                                                 
         10 Anju Gurung                                                 5 New Baneshwor        9842145680           Staff                                                                                                                                                                                   
         17 Bishal Tamrakar                                            10 Gwarko               9842845687           VIP                                                                                                                                                                                     
         16 Sabina Thapa                                                5 Jhamsikhel           9842745686           Regular                                                                                                                                                                                 
         20 Nisha Bhattarai                                            10 Kuleshwor            9843145690           VIP                                                                                                                                                                                     

7 rows selected.

SQL> spool off;
