SQL> SELECT TO_CHAR(ORDER_DATE, 'MON-YYYY') AS MONTH_YEAR,
  2  SUM(FINAL_AMOUNT) AS TOTAL_REVENUE
  3  FROM ordertable
  4  GROUP BY TO_CHAR(ORDER_DATE, 'MON-YYYY')
  5  ORDER BY TO_DATE(TO_CHAR(ORDER_DATE, 'MON-YYYY'), 'MON-YYYY');

MONTH_YEAR        TOTAL_REVENUE                                                                                                                                                                                                                                                                                                                                                                                 
----------------- -------------                                                                                                                                                                                                                                                                                                                                                                                 
JAN-2023                 493.95                                                                                                                                                                                                                                                                                                                                                                                 
FEB-2023                  44.98                                                                                                                                                                                                                                                                                                                                                                                 
MAR-2023                 389.97                                                                                                                                                                                                                                                                                                                                                                                 
APR-2023                 132.98                                                                                                                                                                                                                                                                                                                                                                                 
MAY-2023                1846.38                                                                                                                                                                                                                                                                                                                                                                                 
JUN-2023                 912.91                                                                                                                                                                                                                                                                                                                                                                                 
JUL-2023                 539.94                                                                                                                                                                                                                                                                                                                                                                                 
AUG-2023                1389.85                                                                                                                                                                                                                                                                                                                                                                                 
SEP-2023                 330.48                                                                                                                                                                                                                                                                                                                                                                                 
OCT-2023                 215.98                                                                                                                                                                                                                                                                                                                                                                                 
NOV-2023                  89.97                                                                                                                                                                                                                                                                                                                                                                                 

11 rows selected.

SQL> spool off;
